/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.3 and the Signal Processing Toolbox 6.21.
 * Generated on: 04-May-2019 10:56:22
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 32
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2014a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int32 filter coefficients.
 */
const int BL = 32;
const int32_T B[32] = {
      -1918880,    -9522326,   -22691061,   -35621649,   -35297344,   -12158025,
      27514998,    56873981,    43755862,   -20199828,   -98250136,  -119191987,
     -22191623,   191978594,   444061325,   614227399,   614227399,   444061325,
     191978594,   -22191623,  -119191987,   -98250136,   -20199828,    43755862,
      56873981,    27514998,   -12158025,   -35297344,   -35621649,   -22691061,
      -9522326,    -1918880
};
