/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.3 and the Signal Processing Toolbox 6.21.
 * Generated on: 03-May-2019 09:48:59
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 33
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2014a\extern\include\tmwtypes.h 
 */
const int BL = 33;
const real64_T B[33] = {
   0.005829120283757,  0.01255944633587, -0.01118905222459,-0.004984069855165,
    0.01460944791376, 0.002972261017969, -0.02235723882265, 0.004269405247729,
    0.03024556136228, -0.01751275769108, -0.03788117816698,  0.04140722224446,
      0.044219029466, -0.09175732272951, -0.04842009496054,   0.3133506870802,
     0.5498888102979,   0.3133506870802, -0.04842009496054, -0.09175732272951,
      0.044219029466,  0.04140722224446, -0.03788117816698, -0.01751275769108,
    0.03024556136228, 0.004269405247729, -0.02235723882265, 0.002972261017969,
    0.01460944791376,-0.004984069855165, -0.01118905222459,  0.01255944633587,
   0.005829120283757
};
