/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.3 and the Signal Processing Toolbox 6.21.
 * Generated on: 04-May-2019 09:40:15
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 17
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2014a\extern\include\tmwtypes.h 
 */
const int BL_f = 17;
const real64_T B_f[17] = {
   -0.03889912042983,  -0.0989032831086, -0.05057915933453,  0.05707198903441,
    0.03926304926069,  -0.1009560689368, -0.03597582128184,   0.3158973242437,
     0.5366937998641,   0.3158973242437, -0.03597582128184,  -0.1009560689368,
    0.03926304926069,  0.05707198903441, -0.05057915933453,  -0.0989032831086,
   -0.03889912042983
};
