/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.3 and the Signal Processing Toolbox 6.21.
 * Generated on: 28-Sep-2019 23:47:07
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 51
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2014a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int32 filter coefficients.
 */
const int bl = 51;
const int32_T b[51] = {
        623817,     1327683,     2431119,     3736734,     4933554,     5529753,
       4900339,     2395565,    -2498026,    -9965377,   -19679389,   -30673693,
     -41314853,   -49410045,   -52458073,   -48020537,   -34165740,    -9903329,
      24470641,    67203656,   115142693,   164033193,   209030830,   245350977,
     268952204,   277135341,   268952204,   245350977,   209030830,   164033193,
     115142693,    67203656,    24470641,    -9903329,   -34165740,   -48020537,
     -52458073,   -49410045,   -41314853,   -30673693,   -19679389,    -9965377,
      -2498026,     2395565,     4900339,     5529753,     4933554,     3736734,
       2431119,     1327683,      623817
};
