/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.3 and the Signal Processing Toolbox 6.21.
 * Generated on: 04-May-2019 09:59:56
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 33
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2014a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int32 filter coefficients.
 */
const int BL = 33;
const int32_T B[33] = {
      -1603179,     6464360,    11530276,    20509895,    33161385,    49640020,
      69940296,    93754781,   120439761,   149024981,   178250980,   206657732,
     232700120,   254850806,   271765408,   282368751,   285979562,   282368751,
     271765408,   254850806,   232700120,   206657732,   178250980,   149024981,
     120439761,    93754781,    69940296,    49640020,    33161385,    20509895,
      11530276,     6464360,    -1603179
};
